### ISSUE TITLE
Exception in ArraySerializer

### ISSUE THREAD

**Issue by CinexUA** [spatie/fractalistic#57] opened 2022-04-12 08:20 UTC
I got an exception in ArraySerializer.
For ex.: "**local.ERROR: Declaration of Spatie\Fractalistic\ArraySerializer::collection(string $resourceKey, array $data): array must be compatible with League\Fractal\Serializer\ArraySerializer::collection(?string $resourceKey, array $data): array**"

In the collection method, you need to add question mark before: "string $resourceKey" which invoke the exception,
because the method changed in "League\Fractal\Serializer\ArraySerializer"
To fix it, you need to add a question mark:
```public function collection(?string $resourceKey, array $data): array``` in 

[screen_1.jpg](https://i.ibb.co/p2MTYz9/Screenshot-from-2022-04-12-10-25-15.png)
[screen_2.jpg](https://i.ibb.co/dgRSmfp/Screenshot-from-2022-04-12-10-28-41.png)
[screen_3.jpg](https://i.ibb.co/jwVc7Cd/Screenshot-from-2022-04-12-10-28-56.png)
[screen_4.jpg](https://i.ibb.co/q7Y23zY/Screenshot-from-2022-04-12-11-15-28.png)

**Comment by freekmurze** [comment] 2022-04-12 08:24
Duplicate of #56

**Closed by freekmurze** 2022-04-12 08:24 UTC
